#15 - GetStorageSlice migrated
artipie/management-api pull request #26
Opened 2020-12-14 09:29 UTC by olenagerasimova

Closes #15 
Migrated `GetStorageSlice` from `artipie`.

2020-12-14 11:22 UTC, olegmoz requested changes
@olenagerasimova thanks, please see one comment regarding new interface name

2020-12-14 11:22 UTC, olegmoz commented on src/main/java/com/artipie/management/RepoStorage.java
> +public interface RepoStorage {
@olenagerasimova `RepoStorage` name does not look ideal to me. Repository storage is something that is returned by this object's method `repoStorage`. Maybe naming it `Storages` or `Repositories` will be better?

2020-12-14 11:44 UTC, olenagerasimova commented
@olegmoz thanks, renamed

2020-12-14 12:27 UTC, olegmoz requested changes
@olenagerasimova thanks, please see the comments

2020-12-14 12:27 UTC, olegmoz commented on src/main/java/com/artipie/management/Storages.java
> + * Repository storage.
@olenagerasimova please update JavaDoc according to new interface name

2020-12-14 12:27 UTC, olegmoz commented on src/main/java/com/artipie/management/api/artifactory/GetStorageSlice.java
> +     * Artipie settings storage.
@olenagerasimova please update JavaDoc for the field

2020-12-14 12:27 UTC, olegmoz commented on src/main/java/com/artipie/management/api/artifactory/GetStorageSlice.java
> +     * @param storage Artipie settings storage
@olenagerasimova please update JavaDoc for the parameter

2020-12-14 16:00 UTC, olenagerasimova commented
@olegmoz thanks, corrected

2020-12-15 05:45 UTC, olegmoz approved these changes
@olenagerasimova thanks, merging

2020-12-15 05:45 UTC, merged